config/routes.rb
FourCash::Application.routes.draw do
  get "charts/index"
  
  match "/charts" => "charts#index", :format => 'json'
  match "/charts/arrays" => "charts#arrays", :format => 'json'

  resources :goals

  resources :transactions

  root :to => "home#index"
  resources :users, :only => [ :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  
  match '/auth/facebook', :as => :auth_facebook
end

app/models/goal.rb
class Goal
  include Mongoid::Document
  field :title, :type => String
  field :date, :type => Date
  field :amount, :type => Float
end

app/models/transaction.rb
class Transaction
  include Mongoid::Document
  field :date, :type => Date
  field :amount, :type => Float
  
  attr_accessible :amount, :date
  validates_numericality_of :amount
  validates_presence_of :amount, :date 
  
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, :type => String
  field :uid, :type => String
  field :name, :type => String
  field :email, :type => String
  attr_accessible :provider, :uid, :name, :email

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    
    @transactions = Transaction.all

    respond_to do |format|
      format.json { render json: @transactions }
    end
    
  end
  
  def arrays 
    transactions = Transaction.all
    
    @arrays = Array.new
    transactions_array = Array.new
    dates_array = Array.new
    
    #CREATE ARRAY OF DATES
    transactions.each do |transaction|
      dates_array.push transaction.date
    end 
    
    #CREATE ARRAY OF TRANSACTIONS
    transactions.each do |transaction|
      transactions_array.push transaction.amount
    end 
    
    @arrays.push(dates_array)
    @arrays.push(transactions_array)
    
    respond_to do |format|
      format.json { render json: @arrays }
    end
    
    
  end
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/new
  # GET /goals/new.json
  def new
    @goal = Goal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/1/edit
  def edit
    @goal = Goal.find(params[:id])
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(params[:goal])

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @goal }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    @goal = Goal.find(params[:id])

    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?

  def index
    @users = User.paginate(:page => params[:page])
  end

    def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charts/index.html.haml
%h1 Charts#index
%p Find me in app/views/charts/index.html.haml

app/views/goals/_form.html.haml
= simple_form_for(@goal) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :date
    = f.input :amount

  .form-actions
    = f.button :submit

app/views/goals/edit.html.haml
%h1 Editing goal

= render 'form'

= link_to 'Show', @goal
\|
= link_to 'Back', goals_path

app/views/goals/index.html.haml
%h1 Listing goals

%table
  %tr
    %th Title
    %th Date
    %th Amount
    %th
    %th
    %th

  - @goals.each do |goal|
    %tr
      %td= goal.title
      %td= goal.date
      %td= goal.amount
      %td= link_to 'Show', goal
      %td= link_to 'Edit', edit_goal_path(goal)
      %td= link_to 'Destroy', goal, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Goal', new_goal_path

app/views/goals/new.html.haml
%h1 New goal

= render 'form'

= link_to 'Back', goals_path

app/views/goals/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @goal.title
%p
  %b Date:
  = @goal.date
%p
  %b Amount:
  = @goal.amount

= link_to 'Edit', edit_goal_path(@goal)
\|
= link_to 'Back', goals_path

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

%h3 Chart

#chart

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Fourcash", root_path, :class => 'brand'
%ul.nav
  %li
    =link_to 'Transactions', transactions_path
    
  %li
    =link_to 'Goals', goals_path

  - if user_signed_in?
    %li
      Logged in as #{current_user.name}
    %li
      = link_to('Logout', signout_path)
  - else
    %li
      = link_to('Login', signin_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Fourcash"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" }
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/transactions/_form.html.haml
= simple_form_for(@transaction) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date, :as => :date
    = f.input :amount

  .form-actions
    = f.button :submit

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th Date
    %th Amount
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.date
      %td= transaction.amount
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete

%br
= link_to 'New Transaction', new_transaction_path, :class => 'btn btn-primary'

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @transaction.date
%p
  %b Amount:
  = @transaction.amount

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/index.html.haml
%h2 Users
- @users.each do |user|
  %br/
  #{link_to user.email, user} signed up #{user.created_at.to_date}

= will_paginate

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}